[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.28"
# auto_detect_solc = true
ffi = true
via-ir = true
optimizerSteps = ''
optimizer = true
optimizer_runs = 1
# solc = "0.8.29"

fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
goerli = "${PROVIDER_URI_GOERLI}"