// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct QuestsData {
  uint256 numberOfQuests;
  uint256 numberOfQuestsGroups;
  uint256 numberOfRewards;
  uint256[] activeQuestGroups;
}

library Quests {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "", name: "Quests", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x7462000000000000000000000000000051756573747300000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0060030120202000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of ()
  Schema constant _keySchema = Schema.wrap(0x0000000000000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint256, uint256[])
  Schema constant _valueSchema = Schema.wrap(0x006003011f1f1f81000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](0);
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](4);
    fieldNames[0] = "numberOfQuests";
    fieldNames[1] = "numberOfQuestsGroups";
    fieldNames[2] = "numberOfRewards";
    fieldNames[3] = "activeQuestGroups";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get numberOfQuests.
   */
  function getNumberOfQuests() internal view returns (uint256 numberOfQuests) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numberOfQuests.
   */
  function _getNumberOfQuests() internal view returns (uint256 numberOfQuests) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set numberOfQuests.
   */
  function setNumberOfQuests(uint256 numberOfQuests) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((numberOfQuests)), _fieldLayout);
  }

  /**
   * @notice Set numberOfQuests.
   */
  function _setNumberOfQuests(uint256 numberOfQuests) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((numberOfQuests)), _fieldLayout);
  }

  /**
   * @notice Get numberOfQuestsGroups.
   */
  function getNumberOfQuestsGroups() internal view returns (uint256 numberOfQuestsGroups) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numberOfQuestsGroups.
   */
  function _getNumberOfQuestsGroups() internal view returns (uint256 numberOfQuestsGroups) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set numberOfQuestsGroups.
   */
  function setNumberOfQuestsGroups(uint256 numberOfQuestsGroups) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((numberOfQuestsGroups)), _fieldLayout);
  }

  /**
   * @notice Set numberOfQuestsGroups.
   */
  function _setNumberOfQuestsGroups(uint256 numberOfQuestsGroups) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((numberOfQuestsGroups)), _fieldLayout);
  }

  /**
   * @notice Get numberOfRewards.
   */
  function getNumberOfRewards() internal view returns (uint256 numberOfRewards) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get numberOfRewards.
   */
  function _getNumberOfRewards() internal view returns (uint256 numberOfRewards) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set numberOfRewards.
   */
  function setNumberOfRewards(uint256 numberOfRewards) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((numberOfRewards)), _fieldLayout);
  }

  /**
   * @notice Set numberOfRewards.
   */
  function _setNumberOfRewards(uint256 numberOfRewards) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((numberOfRewards)), _fieldLayout);
  }

  /**
   * @notice Get activeQuestGroups.
   */
  function getActiveQuestGroups() internal view returns (uint256[] memory activeQuestGroups) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Get activeQuestGroups.
   */
  function _getActiveQuestGroups() internal view returns (uint256[] memory activeQuestGroups) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (SliceLib.getSubslice(_blob, 0, _blob.length).decodeArray_uint256());
  }

  /**
   * @notice Set activeQuestGroups.
   */
  function setActiveQuestGroups(uint256[] memory activeQuestGroups) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((activeQuestGroups)));
  }

  /**
   * @notice Set activeQuestGroups.
   */
  function _setActiveQuestGroups(uint256[] memory activeQuestGroups) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, EncodeArray.encode((activeQuestGroups)));
  }

  /**
   * @notice Get the length of activeQuestGroups.
   */
  function lengthActiveQuestGroups() internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get the length of activeQuestGroups.
   */
  function _lengthActiveQuestGroups() internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 32;
    }
  }

  /**
   * @notice Get an item of activeQuestGroups.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemActiveQuestGroups(uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Get an item of activeQuestGroups.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemActiveQuestGroups(uint256 _index) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 32, (_index + 1) * 32);
      return (uint256(bytes32(_blob)));
    }
  }

  /**
   * @notice Push an element to activeQuestGroups.
   */
  function pushActiveQuestGroups(uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Push an element to activeQuestGroups.
   */
  function _pushActiveQuestGroups(uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, abi.encodePacked((_element)));
  }

  /**
   * @notice Pop an element from activeQuestGroups.
   */
  function popActiveQuestGroups() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Pop an element from activeQuestGroups.
   */
  function _popActiveQuestGroups() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 32);
  }

  /**
   * @notice Update an element of activeQuestGroups at `_index`.
   */
  function updateActiveQuestGroups(uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update an element of activeQuestGroups at `_index`.
   */
  function _updateActiveQuestGroups(uint256 _index, uint256 _element) internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    unchecked {
      bytes memory _encoded = abi.encodePacked((_element));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 32), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Get the full data.
   */
  function get() internal view returns (QuestsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get() internal view returns (QuestsData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 numberOfQuests,
    uint256 numberOfQuestsGroups,
    uint256 numberOfRewards,
    uint256[] memory activeQuestGroups
  ) internal {
    bytes memory _staticData = encodeStatic(numberOfQuests, numberOfQuestsGroups, numberOfRewards);

    EncodedLengths _encodedLengths = encodeLengths(activeQuestGroups);
    bytes memory _dynamicData = encodeDynamic(activeQuestGroups);

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 numberOfQuests,
    uint256 numberOfQuestsGroups,
    uint256 numberOfRewards,
    uint256[] memory activeQuestGroups
  ) internal {
    bytes memory _staticData = encodeStatic(numberOfQuests, numberOfQuestsGroups, numberOfRewards);

    EncodedLengths _encodedLengths = encodeLengths(activeQuestGroups);
    bytes memory _dynamicData = encodeDynamic(activeQuestGroups);

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(QuestsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.numberOfQuests, _table.numberOfQuestsGroups, _table.numberOfRewards);

    EncodedLengths _encodedLengths = encodeLengths(_table.activeQuestGroups);
    bytes memory _dynamicData = encodeDynamic(_table.activeQuestGroups);

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(QuestsData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.numberOfQuests, _table.numberOfQuestsGroups, _table.numberOfRewards);

    EncodedLengths _encodedLengths = encodeLengths(_table.activeQuestGroups);
    bytes memory _dynamicData = encodeDynamic(_table.activeQuestGroups);

    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 numberOfQuests, uint256 numberOfQuestsGroups, uint256 numberOfRewards) {
    numberOfQuests = (uint256(Bytes.getBytes32(_blob, 0)));

    numberOfQuestsGroups = (uint256(Bytes.getBytes32(_blob, 32)));

    numberOfRewards = (uint256(Bytes.getBytes32(_blob, 64)));
  }

  /**
   * @notice Decode the tightly packed blob of dynamic data using the encoded lengths.
   */
  function decodeDynamic(
    EncodedLengths _encodedLengths,
    bytes memory _blob
  ) internal pure returns (uint256[] memory activeQuestGroups) {
    uint256 _start;
    uint256 _end;
    unchecked {
      _end = _encodedLengths.atIndex(0);
    }
    activeQuestGroups = (SliceLib.getSubslice(_blob, _start, _end).decodeArray_uint256());
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   * @param _encodedLengths Encoded lengths of dynamic fields.
   * @param _dynamicData Tightly packed dynamic fields.
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths _encodedLengths,
    bytes memory _dynamicData
  ) internal pure returns (QuestsData memory _table) {
    (_table.numberOfQuests, _table.numberOfQuestsGroups, _table.numberOfRewards) = decodeStatic(_staticData);

    (_table.activeQuestGroups) = decodeDynamic(_encodedLengths, _dynamicData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord() internal {
    bytes32[] memory _keyTuple = new bytes32[](0);

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    uint256 numberOfQuests,
    uint256 numberOfQuestsGroups,
    uint256 numberOfRewards
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(numberOfQuests, numberOfQuestsGroups, numberOfRewards);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(uint256[] memory activeQuestGroups) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(activeQuestGroups.length * 32);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(uint256[] memory activeQuestGroups) internal pure returns (bytes memory) {
    return abi.encodePacked(EncodeArray.encode((activeQuestGroups)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 numberOfQuests,
    uint256 numberOfQuestsGroups,
    uint256 numberOfRewards,
    uint256[] memory activeQuestGroups
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(numberOfQuests, numberOfQuestsGroups, numberOfRewards);

    EncodedLengths _encodedLengths = encodeLengths(activeQuestGroups);
    bytes memory _dynamicData = encodeDynamic(activeQuestGroups);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple() internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](0);

    return _keyTuple;
  }
}
