// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CraftingRecipe, CraftingRecipeData } from "./tables/CraftingRecipe.sol";
import { ActiveStoves } from "./tables/ActiveStoves.sol";
import { StackableItem } from "./tables/StackableItem.sol";
import { ItemInfo, ItemInfoData } from "./tables/ItemInfo.sol";
import { Inventory } from "./tables/Inventory.sol";
import { LandInfo, LandInfoData } from "./tables/LandInfo.sol";
import { LandItemCookingState, LandItemCookingStateData } from "./tables/LandItemCookingState.sol";
import { LandTablesAndChairs, LandTablesAndChairsData } from "./tables/LandTablesAndChairs.sol";
import { LandItem, LandItemData } from "./tables/LandItem.sol";
import { LandPermissions } from "./tables/LandPermissions.sol";
import { LandCell } from "./tables/LandCell.sol";
import { ConfigAddresses, ConfigAddressesData } from "./tables/ConfigAddresses.sol";
import { CafeCosmosConfig, CafeCosmosConfigData } from "./tables/CafeCosmosConfig.sol";
import { TransformationCategories } from "./tables/TransformationCategories.sol";
import { Transformations, TransformationsData } from "./tables/Transformations.sol";
import { WaterController, WaterControllerData } from "./tables/WaterController.sol";
import { LevelReward, LevelRewardData } from "./tables/LevelReward.sol";
import { ClaimedLevels } from "./tables/ClaimedLevels.sol";
import { Quests, QuestsData } from "./tables/Quests.sol";
import { RewardCollection } from "./tables/RewardCollection.sol";
import { QuestCollection, QuestCollectionData } from "./tables/QuestCollection.sol";
import { Reward, RewardData } from "./tables/Reward.sol";
import { QuestGroup, QuestGroupData } from "./tables/QuestGroup.sol";
import { Quest, QuestData } from "./tables/Quest.sol";
import { QuestTask, QuestTaskData } from "./tables/QuestTask.sol";
import { LandQuestGroups, LandQuestGroupsData } from "./tables/LandQuestGroups.sol";
import { LandQuestTaskProgress, LandQuestTaskProgressData } from "./tables/LandQuestTaskProgress.sol";
import { LandQuestGroup, LandQuestGroupData } from "./tables/LandQuestGroup.sol";
import { LandQuest, LandQuestData } from "./tables/LandQuest.sol";
import { Catalogue } from "./tables/Catalogue.sol";
import { CatalogueItem, CatalogueItemData } from "./tables/CatalogueItem.sol";
import { GuildExists } from "./tables/GuildExists.sol";
import { GuildInvitation } from "./tables/GuildInvitation.sol";
import { MarketplaceListings, MarketplaceListingsData } from "./tables/MarketplaceListings.sol";
import { MarketplaceNonce, MarketplaceNonceData } from "./tables/MarketplaceNonce.sol";
import { GuildsNonce } from "./tables/GuildsNonce.sol";
import { PlayerGuild, PlayerGuildData } from "./tables/PlayerGuild.sol";
import { PlayerTotalEarned } from "./tables/PlayerTotalEarned.sol";
import { Vrgda, VrgdaData } from "./tables/Vrgda.sol";
