// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CatalogueItemPurchaseDTO, CatalogueItemDTO } from "../../libraries/Types.sol";

/**
 * @title ICatalogueSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICatalogueSystem {
  function purchaseCatalogueItem(uint256 landId, uint256 itemId, uint256 quantity) external;

  function purchaseCatalogueItems(uint landId, CatalogueItemPurchaseDTO[] calldata items) external;

  function getTotalCostAndSufficientBalanceToPurchaseItem(
    uint256 landId,
    uint256 itemId,
    uint256 quantity
  ) external view returns (bool sufficient, uint256 totalCost);

  function getTotalCostAndSufficientBalanceToPurchaseItems(
    uint256 landId,
    CatalogueItemPurchaseDTO[] calldata items
  ) external view returns (bool sufficient, uint256 totalCost);

  function getTotalCost(CatalogueItemPurchaseDTO[] calldata items) external view returns (uint256 totalCost);

  function upsertCatalogueItems(CatalogueItemDTO[] calldata items) external;
}
