// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CraftingRecipeDTO } from "../../libraries/LibCraftingStorage.sol";

/**
 * @title ICraftingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICraftingSystem {
  function craftRecipe(uint256 landId, uint256 output) external;

  function createRecipes(CraftingRecipeDTO[] calldata recipes) external;

  function createRecipe(CraftingRecipeDTO calldata recipe) external;

  function removeRecipe(CraftingRecipeDTO calldata recipe) external;
}
