// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { GuildDTO } from "../../libraries/LibGuild.sol";

/**
 * @title IGuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGuildSystem {
  function guildNameInUse(string memory guildName) external view returns (bool);

  function guildNameHasValidCharacters(string memory guildName) external pure returns (bool);

  function createGuild(uint256 landId, string memory guildName) external returns (uint32 guildId);

  function getAllGuilds() external view returns (GuildDTO[] memory guilds);

  function getGuildNameHash(string memory guildName) external pure returns (bytes32);

  function getGuildIdByName(string memory guildName) external view returns (uint32 guildId);

  function exitGuild(uint256 landId) external;

  function setNewGuildAdmin(uint256 landId, uint256 newAdminId) external;

  function claimGuildAdmin(uint256 landId) external;

  function inviteToGuild(uint256 landId, uint256 invitedLandId) external;

  function acceptGuildInvitation(uint256 landId, uint32 guildId) external;

  function kickFromGuild(uint256 landId, uint256 kickedLandId) external;
}
