// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IGuildSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGuildSystem {
  function createGuild(uint256 landId, string memory guildName) external returns (uint8 guildId);

  function exitGuild(uint256 landId) external;

  function inviteToGuild(uint256 landId, uint256 invitedLandId) external;

  function acceptGuildInvitation(uint256 landId, string memory guildName) external;

  function kickFromGuild(uint256 landId, uint256 kickedLandId) external;

  function getGuildId(string memory guildName) external pure returns (uint8);
}
