// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LandQuestGroupDTO } from "../../libraries/LibLandQuests.sol";

/**
 * @title ILandQuestsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILandQuestsSystem {
  function activateLandQuestGroup(uint256 landId, uint256 questGroupId) external;

  function removeAllExpiredQuestGroups(uint256 landId) external;

  function getActiveLandQuestGroups(uint256 landId) external view returns (LandQuestGroupDTO[] memory);

  function getLandQuestGroup(uint256 landId, uint256 questGroupId) external view returns (LandQuestGroupDTO memory);

  function activateAllQuestGroups(uint256 landId) external;
}
