// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILandItemInteractionSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILandItemInteractionSystem {
  function placeItem(uint256 landId, uint256 x, uint256 y, uint256 itemId) external;

  function removeItem(uint256 landId, uint256 x, uint256 y) external;

  function moveItem(uint256 landId, uint256 srcX, uint256 srcY, uint256 dstX, uint256 dstY) external;

  function timestampCheck() external;

  function toggleRotation(uint256 landId, uint256 x, uint256 y, uint256 z) external;
}
