// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILandItemsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILandItemsSystem {
  function itemBalanceOf(uint256 landId, uint256 itemId) external view returns (uint256);

  function itemBalanceOfBatch(uint256 landId, uint256[] memory ids) external view returns (uint256[] memory);

  function depositItems(uint256 landId, uint256[] memory itemIds, uint256[] memory amounts) external;

  function withdrawItems(uint256 landId, uint256[] memory itemIds, uint256[] memory amounts) external;
}
