// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LandItemDTO, PlayerTotalEarnedDTO } from "../../libraries/LandDTOs.sol";

/**
 * @title ILandViewSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILandViewSystem {
  function getLandItems(uint256 landId, uint256 x, uint256 y) external view returns (LandItemDTO[] memory landItems);

  function getRotation(uint256 landId, uint256 x, uint256 y) external view returns (bool);

  function getPlacementTime(uint256 landId, uint x, uint y) external view returns (uint256);

  function getActiveTables(uint256 landId) external view returns (uint256);

  function getTablesOfChairs(uint256 landId, uint256 x, uint256 y) external view returns (uint256[3] memory);

  function getChairsOfTables(uint256 landId, uint256 x, uint256 y) external view returns (uint256[3] memory);

  function getTotalEarned(uint256 landId) external view returns (PlayerTotalEarnedDTO memory playerTotalEarned);

  function getLandItems3d(uint256 landId) external view returns (LandItemDTO[][][] memory land3d);
}
