// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { LevelRewardDTO } from "../../libraries/Types.sol";

/**
 * @title ILevelingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILevelingSystem {
  function unlockLevel(uint256 landId, uint256 level) external;

  function unlockLevels(uint256 landId, uint256[] calldata levels) external;

  function unlockAllLevels(uint256 landId) external;

  function upsertLevelRewards(LevelRewardDTO[] calldata levelRewards) external;

  function upsertLevelReward(LevelRewardDTO calldata levelReward) external;
}
