// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { MarketPlaceListingDTO } from "../../libraries/Types.sol";

/**
 * @title IMarketplaceSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IMarketplaceSystem {
  function listItem(uint256 landId, uint256 itemId, uint256 price, uint256 quantity) external;

  function buyItem(uint256 landId, uint256 listingId, uint256 quantity) external payable;

  function cancelListing(uint256 landId, uint256 listingId) external;

  function editListing(uint256 landId, uint256 listingId, uint256 price, uint256 quantity) external;

  function getListing(uint256 listingId) external view returns (MarketPlaceListingDTO memory marketPlaceListing);

  function getAllListings() external view returns (MarketPlaceListingDTO[] memory marketPlaceListings);
}
