// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IQuestsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IQuestsSystem {
  function createWeeklyQuestIfNotExists() external;

  function createDailyQuestIfNotExists() external;

  function getAllActiveQuestGroupIds() external view returns (uint256[] memory questGroupIds);
}
