// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { TransformationDTO } from "../../systems/interfaces/ITransformationsSystem.sol";
import { TransformationsData } from "../index.sol";

/**
 * @title ITransformationsSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITransformationsSystem {
  function setTransformations(TransformationDTO[] calldata newTransformations) external;

  function setTransformation(TransformationDTO calldata newTransformation) external;

  function getTransformation(
    uint256 base,
    uint256 input
  ) external view returns (TransformationsData memory transformation);
}
