// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IVrgdaSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVrgdaSystem {
  function setVrgdaParameters(int256 _targetPrice, int256 _priceDecayPercent, int256 _perTimeUnit) external;
}
