// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IWaterControllerSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWaterControllerSystem {
  function InitialiseWaterController(
    address _axiomV2QueryAddress,
    uint64 _callbackSourceChainId,
    bytes32 _querySchema
  ) external;

  function axiomV2QueryAddress() external view returns (address);

  function setAxionV2QueryAddress(address _axiomV2QueryAddress) external;

  function axiomV2Callback(
    uint64 sourceChainId,
    address caller,
    bytes32 querySchema,
    uint256 queryId,
    bytes32[] calldata axiomResults,
    bytes calldata extraData
  ) external;

  function axiomV2OffchainCallback(
    uint64 sourceChainId,
    address caller,
    bytes32 querySchema,
    uint256 queryId,
    bytes32[] calldata axiomResults,
    bytes calldata extraData
  ) external;

  function getWaterYieldTime() external view returns (uint256);

  function setWaterControllerParameters(
    uint256 numSamples,
    uint256 blockInterval,
    uint256 minYieldTime,
    uint256 maxYieldTime,
    uint256 endBlockSlippage,
    int256 minDelta,
    int256 maxDelta
  ) external;
}
