// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";
import { ICatalogueSystem } from "./ICatalogueSystem.sol";
import { ICraftingSystem } from "./ICraftingSystem.sol";
import { IGuildSystem } from "./IGuildSystem.sol";
import { ILandConfigSystem } from "./ILandConfigSystem.sol";
import { ILandCreationSystem } from "./ILandCreationSystem.sol";
import { ILandERC1155HolderSystem } from "./ILandERC1155HolderSystem.sol";
import { ILandItemInteractionSystem } from "./ILandItemInteractionSystem.sol";
import { ILandItemsSystem } from "./ILandItemsSystem.sol";
import { ILandQuestsSystem } from "./ILandQuestsSystem.sol";
import { ILandScenarioUserTestingSystem } from "./ILandScenarioUserTestingSystem.sol";
import { ILandTokensSystem } from "./ILandTokensSystem.sol";
import { ILandViewSystem } from "./ILandViewSystem.sol";
import { ILevelingSystem } from "./ILevelingSystem.sol";
import { IMarketplaceSystem } from "./IMarketplaceSystem.sol";
import { IQuestsDTOSystem } from "./IQuestsDTOSystem.sol";
import { IQuestsSystem } from "./IQuestsSystem.sol";
import { ITransformationsSystem } from "./ITransformationsSystem.sol";
import { IVrgdaSystem } from "./IVrgdaSystem.sol";
import { IWaterControllerSystem } from "./IWaterControllerSystem.sol";

/**
 * @title IWorld
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  ICatalogueSystem,
  ICraftingSystem,
  IGuildSystem,
  ILandConfigSystem,
  ILandCreationSystem,
  ILandERC1155HolderSystem,
  ILandItemInteractionSystem,
  ILandItemsSystem,
  ILandQuestsSystem,
  ILandScenarioUserTestingSystem,
  ILandTokensSystem,
  ILandViewSystem,
  ILevelingSystem,
  IMarketplaceSystem,
  IQuestsDTOSystem,
  IQuestsSystem,
  ITransformationsSystem,
  IVrgdaSystem,
  IWaterControllerSystem
{}
